// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX7iIzeZzXANf7MwJBrvIZ_q8BN5TUr3U',
    appId: '1:159541613593:web:184fe07edc03b1075b0688',
    messagingSenderId: '159541613593',
    projectId: 'prototypexreal',
    authDomain: 'prototypexreal.firebaseapp.com',
    databaseURL: 'https://prototypexreal-default-rtdb.firebaseio.com',
    storageBucket: 'prototypexreal.appspot.com',
    measurementId: 'G-40YQENEJJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm1PWIChtHya-qXoM3Z2oeGRyF_1poGuw',
    appId: '1:159541613593:android:382acf271a3d8c5b5b0688',
    messagingSenderId: '159541613593',
    projectId: 'prototypexreal',
    databaseURL: 'https://prototypexreal-default-rtdb.firebaseio.com',
    storageBucket: 'prototypexreal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOmdSyU2Yld5G9QKvXxt0_lvt6Far9xD4',
    appId: '1:159541613593:ios:742615bb5e3a5a425b0688',
    messagingSenderId: '159541613593',
    projectId: 'prototypexreal',
    databaseURL: 'https://prototypexreal-default-rtdb.firebaseio.com',
    storageBucket: 'prototypexreal.appspot.com',
    iosBundleId: 'com.example.nsutz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOmdSyU2Yld5G9QKvXxt0_lvt6Far9xD4',
    appId: '1:159541613593:ios:742615bb5e3a5a425b0688',
    messagingSenderId: '159541613593',
    projectId: 'prototypexreal',
    databaseURL: 'https://prototypexreal-default-rtdb.firebaseio.com',
    storageBucket: 'prototypexreal.appspot.com',
    iosBundleId: 'com.example.nsutz',
  );
}
